Update README.md
yayadrian/HA-Harvst-Watermate pull request #4
Opened 2024-06-19 15:00 UTC by andrew-codechimp

Change HACS installation details as you won't be able to just search HACS until you eventually adds to HACS (takes months once you submit).

Fix manual link that had a reference to battery notes.

2024-06-20 20:41 UTC, yayadrian requested changes
Thanks for the PR. Two issues with the UI integration. It only currently works with configuration.yaml

2024-06-20 20:41 UTC, yayadrian commented on README.md
> +In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Harvst Watermate"
It doesn't currently have UI integration so this wouldn't work.

2024-06-20 20:41 UTC, yayadrian commented on README.md
> +* In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Harvst Watermate"
It doesn't currently have UI integration so this wouldn't work.

2024-06-20 21:40 UTC, yayadrian commented
@andrew-codechimp thanks for pointing out the incorrect link to your repo. I've now updated the readme to remove this.

2024-06-20 21:40 UTC, closed without merging

2024-06-21 06:21 UTC, andrew-codechimp commented
Ah yes, I've never done an integration without a UI config flow.  
The search in HACS won't work though as it's not a HACS default repo.